config/routes.rb
Rails.application.routes.draw do
  resources :regions
  resources :volumes
  resources :tasks
  root :to => "tasks#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
    default_scope { order(created_at: :desc) }
    attr_accessor :file_input
end

app/models/volume.rb
class Volume < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: %i[ show edit update destroy ]

  # GET /regions or /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1 or /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions or /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to region_url(@region), notice: "Region was successfully created." }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1 or /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to region_url(@region), notice: "Region was successfully updated." }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1 or /regions/1.json
  def destroy
    @region.destroy

    respond_to do |format|
      format.html { redirect_to regions_url, notice: "Region was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def region_params
      params.require(:region).permit(:title, :timezone)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    send_file @task.filename_output
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    @task.save

    filename = File.join("/tmp", 'test.csv')

    uploaded_io = params[:task][:file_input]

    filename = Rails.root.join('/tmp', @task.id.to_s + "-" + uploaded_io.original_filename)

    File.open(filename, 'wb') do |file|
      file.write(uploaded_io.read)
    end

    @task.status = 'Создана'

    @task.filename_input = filename

    @task.filename_output = Rails.root.join('/tmp', @task.id.to_s + "-output-" + uploaded_io.original_filename)

#    file = File.open(filename,"w"){|f| f.write params[:task][:file_input].read}

#    @task.filename_input = filename

    respond_to do |format|
      if @task.save

        TaskRunningJob.perform_later(@task)

        format.html { redirect_to tasks_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    if @task.filename_input != nil 
      File.delete(@task.filename_input) if File.exist?(@task.filename_input)
    end

    if @task.filename_output != nil
      File.delete(@task.filename_output) if File.exist?(@task.filename_output)
    end

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Задача успешно удалена." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:status, :file_input)
    end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  before_action :set_volume, only: %i[ show edit update destroy ]

  # GET /volumes or /volumes.json
  def index
    @volumes = Volume.all
  end

  # GET /volumes/1 or /volumes/1.json
  def show
  end

  # GET /volumes/new
  def new
    @volume = Volume.new
  end

  # GET /volumes/1/edit
  def edit
  end

  # POST /volumes or /volumes.json
  def create
    @volume = Volume.new(volume_params)

    respond_to do |format|
      if @volume.save
        format.html { redirect_to volume_url(@volume), notice: "Volume was successfully created." }
        format.json { render :show, status: :created, location: @volume }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volumes/1 or /volumes/1.json
  def update
    respond_to do |format|
      if @volume.update(volume_params)
        format.html { redirect_to volume_url(@volume), notice: "Volume was successfully updated." }
        format.json { render :show, status: :ok, location: @volume }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volumes/1 or /volumes/1.json
  def destroy
    @volume.destroy

    respond_to do |format|
      format.html { redirect_to volumes_url, notice: "Volume was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volume
      @volume = Volume.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def volume_params
      params.require(:volume).permit(:code, :begin, :end, :size, :operator, :region, :unn)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/layouts/_header.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="/">Проверка номера на часовой пояс</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            
          <li class="nav-item">
            <%= link_to "Задачи", tasks_path, {:class => "nav-link"} %>
          </li>
            
          <li class="nav-item">
            <%= link_to "Регионы", regions_path, {:class => "nav-link"} %>
          </li>
	


          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Indexmain</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= javascript_include_tag :application %> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/regions/_form.html.erb
<%= form_with(model: region) do |form| %>
  <% if region.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
        <% region.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :timezone, style: "display: block" %>
    <%= form.text_area :timezone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/regions/_region.html.erb
<div id="<%= dom_id region %>">
  <p>
    <strong>Title:</strong>
    <%= region.title %>
  </p>

  <p>
    <strong>Timezone:</strong>
    <%= region.timezone %>
  </p>

</div>

app/views/regions/edit.html.erb
<h1>Редактирование часового пояса</h1>

<%= render "form", region: @region %>

<br>

<div>
  
  <%= link_to "Назад", regions_path %>
</div>

app/views/regions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Регионы и часовые пояса</h1>

<table class="table table-bordered">
<thead>
  <tr>
    <th>№</th>
    <th>Наименование</th>
    <th>Часовой пояс</th>
    <th colspan="2"></th>
  </tr>
</thead>
<tbody>
  
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.id %></td>        
        <td><%= region.title %></td>
        <td><%= region.timezone %></td>

        <td><%= link_to 'Редактировать', edit_region_path(region) %></td>
        

      </tr>
    <% end %>    
  
</tbody>
</table>

app/views/regions/new.html.erb
<h1>New region</h1>

<%= render "form", region: @region %>

<br>

<div>
  <%= link_to "Back to regions", regions_path %>
</div>

app/views/regions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @region %>

<div>
  <%= link_to "Edit this region", edit_region_path(@region) %> |
  <%= link_to "Back to regions", regions_path %>

  <%= button_to "Destroy this region", @region, method: :delete %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <p>
    <%= form.label "Выбрать файл", style: "display: block" %>
    <%= form.file_field :file_input %>
  </p>

  <div>
    <%= form.submit "Создать"%>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
<p>
  <strong>Status:</strong>
  <%= task.status %>
</p>
<p>
  <strong>Filename input:</strong>
  <%= task.filename_input %>
</p>



</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Задачи</h1>


<%= link_to "Добавить задачу", new_task_path %>

<table class="table table-bordered">
<thead>
  <tr>
    <th>№</th>
    <th>Дата начала</th>
    <th>Дата завершения</th>
    <th>Статус</th>
    <th colspan="2"></th>
  </tr>
</thead>
<tbody>
  
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.created_at %></td>
        <td><%= task.updated_at %></td>
        <td><%= task.status %></td>
<% if task.status == "Выполнена" %>
        <td><%= link_to 'Выгрузить результат', task %></td>
        <td><%= button_to 'Удалить', task, method: :delete, data: { confirm: 'Подтвердить?' } %></td>
<% end %>
      </tr>
    <% end %>    
  
</tbody>
</table>

app/views/tasks/new.html.erb
<h1>Новая задача</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Назад", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

app/views/volumes/_form.html.erb
<%= form_with(model: volume) do |form| %>
  <% if volume.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(volume.errors.count, "error") %> prohibited this volume from being saved:</h2>

      <ul>
        <% volume.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.number_field :code %>
  </div>

  <div>
    <%= form.label :begin, style: "display: block" %>
    <%= form.number_field :begin %>
  </div>

  <div>
    <%= form.label :end, style: "display: block" %>
    <%= form.number_field :end %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.number_field :size %>
  </div>

  <div>
    <%= form.label :operator, style: "display: block" %>
    <%= form.text_field :operator %>
  </div>

  <div>
    <%= form.label :region, style: "display: block" %>
    <%= form.text_field :region %>
  </div>

  <div>
    <%= form.label :unn, style: "display: block" %>
    <%= form.text_field :unn %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/volumes/_volume.html.erb
<div id="<%= dom_id volume %>">
  <p>
    <strong>Code:</strong>
    <%= volume.code %>
  </p>

  <p>
    <strong>Begin:</strong>
    <%= volume.begin %>
  </p>

  <p>
    <strong>End:</strong>
    <%= volume.end %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= volume.size %>
  </p>

  <p>
    <strong>Operator:</strong>
    <%= volume.operator %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= volume.region %>
  </p>

  <p>
    <strong>Unn:</strong>
    <%= volume.unn %>
  </p>

</div>

app/views/volumes/edit.html.erb
<h1>Editing volume</h1>

<%= render "form", volume: @volume %>

<br>

<div>
  <%= link_to "Show this volume", @volume %> |
  <%= link_to "Back to volumes", volumes_path %>
</div>

app/views/volumes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Volumes</h1>

<div id="volumes">
  <% @volumes.each do |volume| %>
    <%= render volume %>
    <p>
      <%= link_to "Show this volume", volume %>
    </p>
  <% end %>
</div>

<%= link_to "New volume", new_volume_path %>

app/views/volumes/new.html.erb
<h1>New volume</h1>

<%= render "form", volume: @volume %>

<br>

<div>
  <%= link_to "Back to volumes", volumes_path %>
</div>

app/views/volumes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @volume %>

<div>
  <%= link_to "Edit this volume", edit_volume_path(@volume) %> |
  <%= link_to "Back to volumes", volumes_path %>

  <%= button_to "Destroy this volume", @volume, method: :delete %>
</div>